# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/ip/skull_rom/skull_rom.xci
# IP: The module: 'skull_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/ip/skull_rom/skull_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'skull_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/ip/skull_rom/skull_rom.xci
# IP: The module: 'skull_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/ip/skull_rom/skull_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'skull_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
