webtalk_init -webtalk_dir E:/edinburgh/DigitalSystemDesign/Assessment1/Assessment1.sim/sim_1/behav/xsim/xsim.dir/Wrapper_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Oct 28 16:16:41 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6992ef77-7a7b-48a5-8771-6be93ad2ff1b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "df9c420780634471ab6c87ebdb98e3a5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2494 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.50_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10888_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2332640456 -regid "" -xml E:/edinburgh/DigitalSystemDesign/Assessment1/Assessment1.sim/sim_1/behav/xsim/xsim.dir/Wrapper_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/edinburgh/DigitalSystemDesign/Assessment1/Assessment1.sim/sim_1/behav/xsim/xsim.dir/Wrapper_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/edinburgh/DigitalSystemDesign/Assessment1/Assessment1.sim/sim_1/behav/xsim/xsim.dir/Wrapper_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
