# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.cache/wt [current_project]
set_property parent.project_path E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/edinburgh/DigitalSystemDesign/SnakeGame/resource/skull_ip.coe
read_verilog -library xil_defaultlib {
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/new/Circle.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/new/Death_Block.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/new/Display_Snake.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/new/Eagle_Move.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/imports/new/Generic_counter.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/new/Head.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/new/Head_Move.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/new/Master_StateMachine.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/imports/new/Muliplexer_4way.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/new/Navigation_StateMachine.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/new/Reach_Target.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/new/Score.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/imports/new/Seg7Display.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/new/Snake_Control.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/imports/new/SomeLogic.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/new/Speed_Counter.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/new/Target_Generator.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/new/Timing.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/imports/new/VGA_Interface.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/new/VGA_Wrapper.v
  E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/new/Top_Wrapper.v
}
read_ip -quiet E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/ip/skull_rom/skull_rom.xci
set_property used_in_implementation false [get_files -all e:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/sources_1/ip/skull_rom/skull_rom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/constrs_1/imports/new/LinkedSM_constraints.xdc
set_property used_in_implementation false [get_files E:/edinburgh/DigitalSystemDesign/SnakeGame/SnakeGame.srcs/constrs_1/imports/new/LinkedSM_constraints.xdc]


synth_design -top Top_Wrapper -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Wrapper_utilization_synth.rpt -pb Top_Wrapper_utilization_synth.pb"
